### ISSUE TITLE
Classify a find

### ISSUE THREAD

**Issue by coreation** [weopendata/medea#12]
Enable classifications of a find, back-end changes that allow creating new classifications and agree/disagree-ing with classifications are in place.

**Comment by thgh** [comment]
API:
POST obj/../cls/../agree: Removes disagree vote if present, adds agree vote if not present
POST obj/../cls/../disagree: Removes agree vote if present, adds disagree vote if not present
DELETE obj/../cls/../agree: Removes agree vote if present
DELETE obj/../cls/../disagree: Removes disagree vote if present

**Comment by thgh** [comment]
Closed in 6b1a8da
