### ISSUE TITLE
Complete Object model

### ISSUE THREAD

**Issue by coreation** [weopendata/medea#34]
- [x] Front-end object inscription (create/edit) ( @thgh ):
- [x] Add inscription type (object['inscription'])
- [x] Edit the dim-input to match with the new expected names (dimensionUnit, measurementValue, dimensionType)

**Comment by thgh** [comment]
Inscription en dimensions worden geconvert naar iets handiger om te bewerken in finds.create.

Beide zijn in stap 3 te bewerken.
