### ISSUE TITLE
Complete productionClassification model

### ISSUE THREAD

**Issue by coreation** [weopendata/medea#35]
* [x] productionClassification properties have been changed to their proper name from the crosswalk (see linked commit below)
* [x] Front-end needs to take these into account ( @thgh )
* [x] Add culture as a property (productionClassificationCulturePeople)

- [x] Add a list of values for the CulturePeople

* [x] Take into account the crosswalk updates in our code:

Note: @thgh change middle dropdown component in the classification, change to culture(people)

* pClassificationNation => pClass..RulerNation
* pClas...Period => pClass..Century

**Comment by thgh** [comment]
period => culturepeople
