### ISSUE TITLE
Photo upload

### ISSUE THREAD

**Issue by thgh** [weopendata/medea#5]
- [x] Save images from POST request 
- [x] Resize to 640x480 with imagemagick & save original
- [x] Return url to images in findEvent list

Expected input:
```
findEvent.object.images = [{
    "name": "imagename.png",
    "src": "data:image/png;base64,....."
}]
```

**Comment by coreation** [comment]
Images are now passed in the images array, with the following structure:
[
"identifier" => uri_to_image
]

This is subject to change as in the datamodel there's room for additional properties such as rights, but this is not taken into account at this moment.
