### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by thgh** [weopendata/medea#61]
- [x] Total count of finds
- [x] Validated finds
- [x] Total count of classifications
- [ ] Display data on the admin page

**Comment by coreation** [comment]
I'd suggest api/statistics?type=finds, later on we can add people, publications and any small statistics on objects they'd like without having to add different api endpoints.

**Comment by thgh** [comment]
If it doesn't add much to the loading time, it could be added in blade on the homepage?

**Comment by coreation** [comment]
Sure thing, i'm not sure how long it will take, but we'll soon find out.
