### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by coreation** [weopendata/medea#65]
Allow for a grid to be displayed for a certain search.

* [x] Save the location with a smaller accuracy (for now , round up the lat lon to 1 tenth, creating 11x7km rectangular buckets)
* [x] Return a JSON response of grids and their counts
* [x] Create the front-end integration of the heat map

**Comment by coreation** [comment]
@thgh currently the following is returned based on the API request to the finds endpoint:

```
[{
	count: 1,
	gridCenter: "51.1,3.7"
}, {
	count: 1,
	gridCenter: "51,3.2"
}]
```

I think you'll need a full list of the "middle points" of the rectangles to have an easy implementation on the front-end?

**Comment by thgh** [comment]
Looks good. This list looks full enough.

**Comment by coreation** [comment]
Ok, we may have to change a few things towards the next iteration (pass the grid size so it's not front-end hard coded for example) but good to know the back-end is fine for now!
