### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by coreation** [weopendata/medea#7]
The registration back-end and login functionality is already in place.
In order to work this out further, the front-end should first be built:

* [x] Build a registration component that takes into account the provided feedback of the VUB
* [x] Provide a login/logout functionality (e.g. a logout button instead of the login button when a user is logged in.)
* [x] Require authentication to access /finds/create

If there are discrepancies between the necessary registration field and the back-end, they should be listed below.

**Comment by thgh** [comment]
{"firstName":"voor",
"lastName":"achter",
"email":"m@m.m",
"password":"wacht",
"expertise":"Something about my expertise",
"research":"About my research",
"bio":"Some bio",
"passContactInfoToAgency":true,
"showContactInfo":true,
"personType":["detectorist","onderzoeker","expert","registrator"],
"oeerk":"OE/ERK/Metaaldetectorist/1234/12345"}

Hier zitten nog enkele extra velden in
